volumes:
  postgres_volume:
  media_volume:

services:
  postgres_db:
    container_name: "${PROJECT_NAME}_postgres_db"
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data:delegated
    ports:
      - ${DB_HOST_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build: ./backend
    command: >
      sh -c "
      python3 manage.py migrate &&
      gunicorn ${PROJECT_NAME}.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - media_volume:/${PROJECT_NAME}/media:delegated
      - ./backend/entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: ["sh", "-c", "chmod +x /usr/local/bin/entrypoint.sh && /usr/local/bin/entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - DJANGO_SETTINGS_MODULE=${PROJECT_NAME}.settings
      - KDM_CLI_BIN=${KDM_CLI_BIN}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DB_HOST_PORT=${DB_HOST_PORT}
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE}
      - CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    depends_on:
      - web
    environment:
      - NGINX_PORT=${NGINX_PORT}