volumes:
  postgres_kdm_volume:
    external: true

services:
  postgres_db:
    container_name: "${PROJECT_NAME}_postgres_db"
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres_kdm_volume:/var/lib/postgresql/data:delegated
    ports:
      - ${HOST_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}