FROM python:3.10.11-bullseye
EXPOSE 8000
COPY . /sveltedjango
COPY ./public /sveltedjango/media/public
WORKDIR /sveltedjango
RUN pip install --no-cache-dir -r requirements.txt
RUN python3 manage.py collectstatic --noinput