# Generated by Django 5.0.6 on 2024-06-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cert',
            options={'ordering': ['-display_name']},
        ),
        migrations.AlterModelOptions(
            name='dkdm',
            options={'ordering': ['-display_name']},
        ),
    ]
