# Generated by Django 5.0.6 on 2024-06-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_kdmcert_cert_alter_cert_options_dkdm'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
