# Generated by Django 5.0.6 on 2024-06-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_job_status_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
