# Generated by Django 5.0.6 on 2024-06-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_job_options_job_enddate_job_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='ok', max_length=255),
        ),
    ]
