# Generated by Django 5.0.6 on 2024-06-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='outputDir',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
