# Generated by Django 5.0.6 on 2024-06-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_kdm_job_kdm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
