# Generated by Django 5.0.6 on 2024-06-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_kdm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdm',
            name='display_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
