# Generated by Django 5.0.6 on 2024-06-08 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_kdm_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='kdm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.kdm'),
        ),
    ]
