# Generated by Django 5.0.6 on 2024-06-08 06:23

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_job_kdm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdm',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=base.models._dynamic_upload_to),
        ),
    ]
