# Generated by Django 5.0.6 on 2024-06-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_kdm_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kdm',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
