name: Docker Build on Master Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Digital Ocean Droplet via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
        script: |
          # Navigate to your app directory
          cd /path/to/your/app/on/droplet
          
          # Pull the latest changes from the repository
          git pull origin master

          # Create the SSL certificate and key files
          echo "${{ secrets.NGINX_SSL_CERTIFICATE }}" > /root/djangokdm/repo/sveltedjangokdm/nginx/ssl_certificate.crt
          echo "${{ secrets.NGINX_SSL_PRIVATE_KEY }}" > /root/djangokdm/repo/sveltedjangokdm/nginx/private.key.pem
