name: Docker Build on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest      

    steps:
    - name: Pull Repo Into Droplet
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
        script: |
          cd /root/djangokdm/repo/sveltedjangokdm/
          
          # Pull the latest changes from the repository
          git pull origin master

          # Create the SSL certificate and key files
          echo "${{ secrets.NGINX_SSL_CERTIFICATE }}" > /root/djangokdm/repo/sveltedjangokdm/nginx/ssl_certificate.crt
          echo "${{ secrets.NGINX_SSL_PRIVATE_KEY }}" > /root/djangokdm/repo/sveltedjangokdm/nginx/private.key.pem

          # Create the .env file
          echo "${{ secrets.PRODUCTION_ENV }}" > /root/djangokdm/repo/sveltedjangokdm/.env

          # Restart/Rebuild the Docker containers
          docker compose down
          docker compose up --build -d
